<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
      
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rundschreibenNeu = '[{"text":"Dokument-197","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-161","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-4","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-90","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]}]';
        $rundschreibenMeine = '[{"text":"Dokument-197","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-161","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-4","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-90","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]}]';
        $wikiEntries = '[{"text":"Dokument-197","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-161","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-4","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-90","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]}]';
        $documentsNew = '[{"text":"Dokument-197","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-161","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-4","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-90","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]}]';
        $commentsNew = '[{"text":"Dokument-197","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-161","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-4","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-90","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]}]';
        $commentsMy = '[{"text":"Dokument-197","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-161","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-4","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]},{"text":"Dokument-90","tags":[4],"nodes":[{"text":"Variante-51","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-197","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-190","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]},{"text":"Variante-50","tags":[3],"nodes":[{"text":"Anhang-170","tags":[0]},{"text":"Anhang-8","tags":[0]},{"text":"Anhang-135","tags":[0]}]}]}]';
        return view('dashboard', compact('rundschreibenNeu', 'rundschreibenMeine', 'wikiEntries', 'documentsNew','commentsNew', 'commentsMy'));
    }
}
